return {
  "williamboman/mason.nvim",
  opts = {
    ui = {
      border = "rounded",
      width = 0.8,
      height = 0.8,
    },
    opts = {
      ensure_installed = {
        "ansible-language-server",
        "ansible-lint",
        "bash-debug-adapter",
        "bash-language-server",
        "beautysh",
        "debugpy",
        "delve",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "erb-formatter",
        "erb-lint",
        "eslint-lsp",
        "gofumpt",
        "goimports",
        "gopls",
        "hadolint",
        "java-debug-adapter",
        "java-test",
        "jdtls",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint",
        "markdownlint-cli2",
        "marksman",
        "prettier",
        "pyright",
        "rubocop",
        "ruby-lsp",
        "ruff",
        "ruff-lsp",
        "shfmt",
        "solargraph",
        "stylua",
        "terraform-ls",
        "tflint",
        "typescript-language-server",
        "vtsls",
        "yaml-language-server",
      },
    },
  },
}
