### Shell customization ###

# Prevent brew from cleaning previous version on upgrade
export HOMEBREW_NO_INSTALL_CLEANUP=1

# Set misc. parameters
setopt   extendedglob
autoload -U colors && colors

# Ensure permissions are correct for ZSH completion
autoload -U compaudit
[[ -n "$(compaudit)" ]] && compaudit | xargs chmod g-w
if [[ `uname` == "Darwin" && -n "$(compaudit)" ]]; then
  printf "Setting right permissions for compinit - "
  sudo chown -RL root:staff /usr/local/share/zsh
fi

# Enable ZSH completion
autoload -Uz compinit && compinit

# Display CWD as title for xterm* terminals
case $TERM in
  xterm*)
  chpwd() {print -Pn "\e]0;%~\a"}
  ;;
esac

# Use touch ID as sudo auth
if [[ `uname` == "Darwin" ]]; then
  source $HOME/.patch_sudo
fi


### Zsh plugins ###

ANTIGEN_BIN=$HOME/.antigen/antigen.zsh

source $ANTIGEN_BIN

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen apply

### Includes ###

function include()
{
  if [[ -f $1 ]]; then
    source $1
  else
    printf "$1 is missing\n"
  fi
}

include $HOME/.zshrc_local
include $HOME/.aliases
include $HOME/.functions

unfunction include

command -v atuin >/dev/null 2>&1 && eval "$(atuin init zsh --disable-up-arrow)"
command -v mise >/dev/null 2>&1 && eval "$(mise activate zsh)"
command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"
